# Generated by Django 4.0.5 on 2022-08-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_leavedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profileimg')),
                ('name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('repassword', models.CharField(max_length=100)),
            ],
        ),
    ]
