# Generated by Django 4.0.5 on 2022-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0012_alter_admindata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='image',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
